version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'daily'
      time: '09:00'
      timezone: 'Asia/Seoul'
    groups:
      turbo:
        patterns:
          - 'turbo'
          - '@turbo/*'
          - 'eslint-plugin-turbo'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      next:
        patterns:
          - 'next'
          - '@next/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
      react-types:
        patterns:
          - '@types/react'
          - '@types/react-dom'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
      radix-ui:
        patterns:
          - '@radix-ui/react-*'
    open-pull-requests-limit: 10
    reviewers:
      - 'wannysim'
    assignees:
      - 'wannysim'
    commit-message:
      prefix: 'chore'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: 'develop'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '09:00'
      timezone: 'Asia/Seoul'
    open-pull-requests-limit: 3
    reviewers:
      - 'wannysim'
    assignees:
      - 'wannysim'
    commit-message:
      prefix: 'ci'
      include: 'scope'
